set timi on
declare
CURSOR CUR1 IS SELECT /*+ RULE */ TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME NOT IN ('CR9020', 'DB_VERSION'); -- CR9020: message resource table
begin
FOR CUR_RECORD IN CUR1 LOOP
EXECUTE IMMEDIATE 'TRUNCATE TABLE "'||CUR_RECORD.TABLE_NAME||'"';
END LOOP;
end;
/
set timi off

exit
