set timi on
declare
CURSOR CUR1 IS SELECT /*+ RULE */ TABLE_NAME FROM USER_TABLES;
begin
FOR CUR_RECORD IN CUR1 LOOP
EXECUTE IMMEDIATE 'ANALYZE TABLE "'||CUR_RECORD.TABLE_NAME||'" ESTIMATE STATISTICS SAMPLE 30 PERCENT';
END LOOP;
end;
/
set timi off
