set timi on
declare
CURSOR CUR1 IS SELECT /*+ RULE */ OBJECT_NAME FROM USER_OBJECTS WHERE OBJECT_TYPE = 'SYNONYM';
begin
FOR CUR_RECORD IN CUR1 LOOP
EXECUTE IMMEDIATE 'DROP SYNONYM "'||CUR_RECORD.OBJECT_NAME||'"';
END LOOP;
end;
/
set timi off
