REM ■定数・変数■
REM 種別
SET TYPE_ENTITY=murata-entity
SET TYPE_WORK=murata-entity-work
SET TYPE_CORE=murata-entity-core
SET TYPE_MULTI=murata-entity-multi

REM バージョン接尾語付き(例:0.5.22core)
SET VERSION_PREFIX_ENTITY=%VERSION_ENTITY%
SET VERSION_PREFIX_WORK=%VERSION_WORK%wk
SET VERSION_PREFIX_CORE=%VERSION_CORE%core
SET VERSION_PREFIX_MULTI=%VERSION_MULTI%multi

SET OLD_VERSION_PREFIX_ENTITY=%OLD_VERSION_ENTITY%
SET OLD_VERSION_PREFIX_WORK=%OLD_VERSION_WORK%wk
SET OLD_VERSION_PREFIX_CORE=%OLD_VERSION_CORE%core
SET OLD_VERSION_PREFIX_MULTI=%OLD_VERSION_MULTI%multi

REM フォルダ名(例:PERSONAL(Ver0.5.52core))
SET DIR_PREFIX_ENTITY=PERSONAL(Ver%VERSION_PREFIX_ENTITY%)
SET DIR_PREFIX_WORK=PERSONAL(Ver%VERSION_PREFIX_WORK%)
SET DIR_PREFIX_CORE=PERSONAL(Ver%VERSION_PREFIX_CORE%)
SET DIR_PREFIX_MULTI=PERSONAL(Ver%VERSION_PREFIX_MULTI%)
SET DIR_PREFIX_SDOLI=PERSONAL(SDOLI)


SET OLD_DIR_PREFIX_ENTITY=PERSONAL(Ver%OLD_VERSION_PREFIX_ENTITY%)
SET OLD_DIR_PREFIX_WORK=PERSONAL(Ver%OLD_VERSION_PREFIX_WORK%)
SET OLD_DIR_PREFIX_CORE=PERSONAL(Ver%OLD_VERSION_PREFIX_CORE%)
SET OLD_DIR_PREFIX_MULTI=PERSONAL(Ver%OLD_VERSION_PREFIX_MULTI%)

SET MARGE_DIR_PREFIX_ENTITY=PERSONAL(Ver%OLD_VERSION_PREFIX_ENTITY%→%VERSION_PREFIX_ENTITY%)
SET MARGE_DIR_PREFIX_WORK=PERSONAL(Ver%OLD_VERSION_PREFIX_WORK%→%VERSION_PREFIX_WORK%)

REM フォルダパス(例:D:\sandbox\public\tools\Entityスクリプト生成ツール\EntityToolPack\0.5.64-sys-079\PERSONAL(Ver0.5.22core))
SET DIR_ENTITY=%DDL_DIR%\%DIR_PREFIX_ENTITY%
SET DIR_WORK=%DDL_DIR%\%DIR_PREFIX_WORK%
SET DIR_CORE=%DDL_DIR%\%DIR_PREFIX_CORE%
SET DIR_MULTI=%DDL_DIR%\%DIR_PREFIX_MULTI%
SET DIR_SDOLI=%DDL_DIR%\%DIR_PREFIX_SDOLI%
REM SMV1370は直下に置く
SET DIR_SMV1370=%DDL_DIR%

SET OLD_DIR_ENTITY=%DDL_DIR%\%OLD_DIR_PREFIX_ENTITY%
SET OLD_DIR_WORK=%DDL_DIR%\%OLD_DIR_PREFIX_WORK%
SET OLD_DIR_CORE=%DDL_DIR%\%OLD_DIR_PREFIX_CORE%
SET OLD_DIR_MULTI=%DDL_DIR%\%OLD_DIR_PREFIX_MULTI%

REM 全実行SQLスクリプトファイル
SET SQL_REPLACEALLOBJECTS=ReplaceAllObjects.sql


REM MV用SQLスクリプトファイル
SET SQLFILEPATH_FORMULTI=%CD%\template\ReplaceAllObjectsForMulti.sql
REM MV作成用SQLスクリプトファイル(ALL)
SET SQLFILEPATH_FORMULTI_ORGALL=all\CreateMaterializedView.sql


REM 差分関連
SET DIR_MARGE=%PACK_DIR%\差分
REM 差分出力ファイル名
SET MARGEFILENAME=ReplaceDifference.sql
